name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: Node.js 14
            NODE_VERSION: 14
          - name: Node.js 16
            NODE_VERSION: 16
          - name: Node.js 18
            NODE_VERSION: 18
      fail-fast: false
    name: ${{ matrix.name }}
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.NODE_VERSION }}
          cache: "yarn" # Enables caching of Yarn dependencies

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Run tests
        run: yarn test

      # - name: Code coverage
      #   run: bash <(curl -s https://codecov.io/bash)
